config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :profiles, only: [:index, :show, :edit]
  devise_for :users, path: '', controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root 'movies#index'

  resources :movies, only: [:index, :show] do 
    member do 
      post :rate
    end
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
    @username = current_user.name
    @recommended_movies = current_user.recommended_movies.limit(10).to_a
    @rated_movies = current_user.movies.page(params[:page]).per(10)
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @user = user.find(param[:id])
    @recommended_movies = @user.recommended_movies
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:Name, :Email)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :Name
    = f.text_field :Name
  .field
    = f.label :Email
    = f.text_field :Email
  .actions
    = f.submit 'Save'

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form'

= link_to 'Show', @profile
\|
= link_to 'Back', profiles_path

app/views/profiles/index.html.haml
.container
  .col-lg-12.col-sm-12
    .card.hovercard
      .card-background
        %img.card-bkimg{:alt => "", :src => "http://lorempixel.com/100/100/people/9/"}/
        / http://lorempixel.com/850/280/people/9/
      .useravatar
        %img{:alt => "", :src => "http://nobleok.org/wp-content/uploads/2014/07/default-profile-female.jpg"}/
      .card-info
        %span.card-title= current_user.name
    / .btn-pref.btn-group.btn-group-justified.btn-group-lg{"aria-label" => "...", :role => "group"}
    /   .btn-group{:role => "group"}
    /     %button#stars.btn.btn-primary{"data-toggle" => "tab", :href => "#tab1", :type => "button"}
    /       %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
    /       .hidden-xs Ratings
    /   .btn-group{:role => "group"}
    /     %button#favorites.btn.btn-default{"data-toggle" => "tab", :href => "#tab2", :type => "button"}
    /       %span.glyphicon.glyphicon-heart{"aria-hidden" => "true"}
    /       .hidden-xs Likes
    /   .btn-group{:role => "group"}
    /     %button#following.btn.btn-default{"data-toggle" => "tab", :href => "#tab3", :type => "button"}
    /       %span.glyphicon.glyphicon-user{"aria-hidden" => "true"}
    /       .hidden-xs Following

    %br 
    
    .panel.panel-default
      .panel-heading Movies Recommended Just For You!
      .panel-body
        .row
          - @recommended_movies.each do |movie|
            = render :partial => 'shared/movie', :locals => {:movie => movie}

    .panel.panel-default
      .panel-heading Rated Movies
      .panel-body
        .row
          - @rated_movies.each do |movie|
            = render :partial => 'shared/movie', :locals => {:movie => movie}
        %center
          = paginate @rated_movies, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm"

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', profiles_path

app/views/profiles/show.html.erb
<link rel="stylesheet" type="text/css" href="/assets/landing.css">
<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"/>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="/assets/landing.js"></script>



<div class="container">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-left">
        <li><a href="#">Home</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Genre <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Thriller</a></li>
            <li><a href="#">Drama</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<br>
<br>
<div class="col-lg-12 col-sm-12">
    <div class="card hovercard">
        <div class="card-background">
            <img class="card-bkimg" alt="" src="http://lorempixel.com/100/100/people/9/">
            <!-- http://lorempixel.com/850/280/people/9/ -->
        </div>
        <div class="useravatar">
            <img alt="" src="http://nobleok.org/wp-content/uploads/2014/07/default-profile-female.jpg">
        </div>
        <div class="card-info"> <span class="card-title">Noha Elshourbagy</span>

        </div>
    </div>
    <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
        <div class="btn-group" role="group">
            <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <div class="hidden-xs">Ratings</div>
            </button>
        </div>
        <div class="btn-group" role="group">
            <button type="button" id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                <div class="hidden-xs">Likes</div>
            </button>
        </div>
        <div class="btn-group" role="group">
            <button type="button" id="following" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <div class="hidden-xs">Following</div>
            </button>
        </div>
    </div>
    <br>
    <br>

     <div class="panel panel-default">
  <div class="panel-heading">Movies Recommended Just For You!</div>
  <div class="panel-body">
     <% @recommended_movies.each do |movie| %>
      <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSPISbJaP5Ic6sbJhxSsQInhXPqyK25pBz2ft7SINTMiPUPNpt1">
        </a>
        <div class="media-body">
            <h4 class="media-heading"> <%= movie.name %></h4>
          <p><%= movie.release_date %> </p>
          <p> <%= movie.Genre %> </p>
          <ul class="list-inline list-unstyled">
            <li><span><i class="glyphicon glyphicon-calendar"></i> 2hrs:44mins </span></li>
            <li>|</li>
            <span><i class="glyphicon glyphicon-eye-open"></i> 2</span>
            <li>|</li>
            <li>
               <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
            </li>
            </ul>
       </div>
</div>
      <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTV9XbP5vJ_BpgRISJ7UCLWLFuDINfuT_ywp3S4eflgU_ZDLoV9">
        </a>
        <div class="media-body">
            <h4 class="media-heading">The Intern(2015)</h4>
          <p>Director:Nancy Meyers , Stars:  Robert De Niro, Anne Hathaway</p>
          <p>Comedy</p>
          <ul class="list-inline list-unstyled">
            <li><span><i class="glyphicon glyphicon-calendar"></i> 2hrs,44mins</span></li>
            <li>|</li>
            <span><i class="glyphicon glyphicon-eye-open"></i> 2</span>
            <li>|</li>
            <li>
               <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
            </li>
            </ul>
    </div>
</div>
      <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="https://www.movieposter.com/posters/archive/tiny/19/MPW-9991">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Spiderman(2002)</h4>
          <p>Director:  Sam Raimi, Stars:Tobey Maguire, Kirsten Dunst, Willem Dafoe</p>
          <p>Action|Adventure</p>
          <ul class="list-inline list-unstyled">
            <li><span><i class="glyphicon glyphicon-calendar"></i> 2hrs:1min </span></li>
            <li>|</li>
            <span><i class="glyphicon glyphicon-eye-open"></i> 2</span>
            <li>|</li>
            <li>
               <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
            </li>
            </ul>
    </div>
</div>